# .github/labels.yml
# Define GitHub labels for issues and pull requests.
# Format: name, color (hex, without #), and description.

# --- Default Labels ---
- name: bug
  color: "d73a4a"
  description: Something isn't working

- name: documentation
  color: "0075ca"
  description: Improvements or additions to documentation

- name: enhancement
  color: "a2eeef"
  description: New feature or request

- name: question
  color: "d876e3"
  description: Further information is requested

- name: wontfix
  color: "ffffff"
  description: This will not be worked on

# --- Priority Labels ---
- name: priority:high
  color: "b60205"
  description: Must be fixed ASAP

- name: priority:medium
  color: "fbca04"
  description: Should be addressed soon

- name: priority:low
  color: "0e8a16"
  description: Low impact or minor issue

# --- Status Labels ---
- name: status:in-progress
  color: "c2e0c6"
  description: Work has started on this item

- name: status:blocked
  color: "f9d0c4"
  description: Blocked by another issue or PR

# --- Area Labels ---
- name: area:golang
  color: "1d76db"
  description: Related to the Go codebase

- name: area:python
  color: "4e9a06"
  description: Related to the Python codebase

- name: area:docs
  color: "5319e7"
  description: Related to documentation or comments

# --- Type Labels ---
- name: type:ci
  color: "e4e669"
  description: Continuous Integration or workflows

- name: type:test
  color: "e4e669"
  description: Testing, test cases, or coverage
