# Server-specific Configuration
# This file contains server-specific settings

# ============================================================================
# Server Settings
# ============================================================================
[server]
# Server name (for display purposes)
name = "Minecraft Server"

# Server port
port = 25565

# Maximum number of players
max_players = 20

# Shutdown timeout (how long to wait for graceful shutdown)
shutdown_timeout = "30s"

# Custom start command (optional, leave empty for default)
start_command = ""

# Custom stop command (optional, leave empty for default)
stop_command = ""

# ============================================================================
# Backup Settings
# ============================================================================
[backup]
# Number of days to retain backups
retention_days = 30

# Enable compression for backups
compression = true

# Enable incremental backups
incremental = true

# ============================================================================
# Maintenance Window
# ============================================================================
[maintenance]
# Maintenance window start time (HH:MM format)
window_start = "02:00"

# Maintenance window end time (HH:MM format)
window_end = "04:00"

# Timezone for maintenance window
timezone = "UTC"